import { useState, useEffect, useCallback } from 'react'
import type { Hypothesis, HypothesisZone } from '../lib/hypothesis'
import { confidenceColor, statusColor, parseHypotheses, mergeHypotheses } from '../lib/hypothesis'

interface HypothesisPanelProps {
  /** Hypotheses are managed in App state and passed down. */
  hypotheses: Hypothesis[]
  setHypotheses: (h: Hypothesis[]) => void
  /** When a zone is clicked, fly to it on the map. */
  onZoneSelect?: (zone: HypothesisZone) => void
}

/**
 * Hypothesis Panel — displays structured reasoning cards generated by the AI analyst.
 *
 * Each card shows:
 *  - Title + statement
 *  - Confidence bar (color-coded)
 *  - Status badge (active / superseded / confirmed / disproven)
 *  - Supporting evidence with source + weight
 *  - Suggested zones (clickable — flies to zone on map)
 *
 * The LLM generates hypotheses by emitting a ```hypothesis JSON block
 * in its response. The panel listens for new chat messages and extracts them.
 */
export function HypothesisPanel({ hypotheses, setHypotheses, onZoneSelect }: HypothesisPanelProps) {
  const [expandedId, setExpandedId] = useState<string | null>(null)

  // Listen for new LLM responses containing hypothesis blocks
  useEffect(() => {
    const handler = (e: Event) => {
      const detail = (e as CustomEvent<{ content: string }>).detail
      if (!detail?.content) return
      const parsed = parseHypotheses(detail.content)
      if (parsed.length > 0) {
        setHypotheses(mergeHypotheses(hypotheses, parsed))
      }
    }
    window.addEventListener('ai:response', handler)
    return () => window.removeEventListener('ai:response', handler)
  }, [hypotheses, setHypotheses])

  // Clear on map clear
  useEffect(() => {
    const handler = () => setHypotheses([])
    window.addEventListener('terrain:clear-all', handler)
    return () => window.removeEventListener('terrain:clear-all', handler)
  }, [setHypotheses])

  const activeHypotheses = hypotheses.filter((h) => h.status === 'active')
  const historicalHypotheses = hypotheses.filter((h) => h.status !== 'active')

  if (hypotheses.length === 0) {
    return (
      <div className="hyp-panel-empty">
        <p className="muted">No hypotheses yet. Ask the AI analyst to assess the situation.</p>
        <p className="muted hint">e.g. "Based on the current analysis, what are the top 3 hypotheses for where the missing person might be?"</p>
      </div>
    )
  }

  return (
    <div className="hyp-panel">
      {activeHypotheses.length > 0 && (
        <div className="hyp-section-label">Active ({activeHypotheses.length})</div>
      )}
      {activeHypotheses.map((h) => (
        <HypothesisCard
          key={h.id}
          hypothesis={h}
          expanded={expandedId === h.id}
          onToggle={() => setExpandedId(expandedId === h.id ? null : h.id)}
          onZoneSelect={onZoneSelect}
        />
      ))}

      {historicalHypotheses.length > 0 && (
        <div className="hyp-section-label muted">History ({historicalHypotheses.length})</div>
      )}
      {historicalHypotheses.map((h) => (
        <HypothesisCard
          key={h.id}
          hypothesis={h}
          expanded={expandedId === h.id}
          onToggle={() => setExpandedId(expandedId === h.id ? null : h.id)}
          onZoneSelect={onZoneSelect}
          dimmed
        />
      ))}
    </div>
  )
}

function HypothesisCard({
  hypothesis: h,
  expanded,
  onToggle,
  onZoneSelect,
  dimmed,
}: {
  hypothesis: Hypothesis
  expanded: boolean
  onToggle: () => void
  onZoneSelect?: (zone: HypothesisZone) => void
  dimmed?: boolean
}) {
  return (
    <div
      className={`hyp-card ${dimmed ? 'hyp-card-dimmed' : ''}`}
      style={{ borderLeftColor: confidenceColor(h.confidence) }}
    >
      <div className="hyp-card-header" onClick={onToggle}>
        <div className="hyp-card-title-row">
          <span className="hyp-card-title">{h.title}</span>
          <span
            className="hyp-status-badge"
            style={{ background: statusColor(h.status) + '30', color: statusColor(h.status) }}
          >
            {h.status}
          </span>
        </div>
        <div className="hyp-confidence-bar">
          <div
            className="hyp-confidence-fill"
            style={{ width: `${h.confidence}%`, background: confidenceColor(h.confidence) }}
          />
          <span className="hyp-confidence-label">{h.confidence}%</span>
        </div>
        <div className="hyp-card-statement">{h.statement}</div>
      </div>

      {expanded && (
        <div className="hyp-card-body">
          {/* Evidence */}
          {h.evidence.length > 0 && (
            <div className="hyp-section">
              <div className="hyp-section-title">Evidence</div>
              {h.evidence.map((e, i) => (
                <div key={i} className="hyp-evidence-item">
                  <span className={`hyp-evidence-weight hyp-weight-${e.weight}`}>
                    {e.weight}
                  </span>
                  <span className="hyp-evidence-source">{e.source}</span>
                  <span className="hyp-evidence-finding">{e.finding}</span>
                </div>
              ))}
            </div>
          )}

          {/* Suggested zones */}
          {h.suggestedZones && h.suggestedZones.length > 0 && (
            <div className="hyp-section">
              <div className="hyp-section-title">Suggested Zones</div>
              {h.suggestedZones.map((z) => (
                <div
                  key={z.id}
                  className="hyp-zone-item"
                  style={{ borderLeftColor: confidenceColor(z.confidence) }}
                  onClick={() => onZoneSelect?.(z)}
                >
                  <div className="hyp-zone-header">
                    <span className="hyp-zone-label">{z.label}</span>
                    <span className="hyp-zone-confidence">{z.confidence}%</span>
                  </div>
                  {z.reasons.length > 0 && (
                    <ul className="hyp-zone-reasons">
                      {z.reasons.map((r, j) => (
                        <li key={j}>{r}</li>
                      ))}
                    </ul>
                  )}
                </div>
              ))}
            </div>
          )}

          {/* Timestamps */}
          <div className="hyp-timestamps muted">
            Created {new Date(h.createdAt).toLocaleTimeString()}
            {h.updatedAt !== h.createdAt && ` · Updated ${new Date(h.updatedAt).toLocaleTimeString()}`}
          </div>
        </div>
      )}
    </div>
  )
}
